FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y libgl1-mesa-glx \
    && pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["python", "model_runner.py"]
